### ISSUE TITLE
About running the full pipeline

### ISSUE THREAD

**Issue by dongho-Han** [PKU-EPIC/HOTrack#1]
Thanks for the nice work and implementation!
I read your paper and got amazed, so I am trying to run your code.
But, I got several questions below.
1. When I read your paper, I thought that the `object pose tracking task` and `hand pose tracking task`, two tasks are running parallel. And, after the optimization, the hand pose gets more accurate. But, When I see your readme, running in full pipeline manner, it seems they are not working in parallel. Am I right? 
2. Also, as the HO3D dataset is very large, I first tried to run the full pipeline with the DexYCB dataset. But, as `objopt_test_DexYCB.yml` and `handopt_test_DexYCB.yml` files are not opened. Can you share the files?

Thanks!

**Comment by JYChen18** [comment]
Thanks for your interest in our work.
1. You are right. The current version doesn't run two tasks in parallel. However, they can be paralleled theoretically, since these two tasks don't rely on each other's prediction.
2. You only need to replace all the `HO3D` with `DexYCB` in these two files.

**Comment by dongho-Han** [comment]
Thanks for the answer. I will try again to reproduce the results.
I'm also curious about the dataset, SimGrasp that you've made.
I sent a mail on 7/3. Can you give any comment on that?
Thanks!
