### ISSUE TITLE
The problem about  Curriculum-DeepSDF

### ISSUE THREAD

**Issue by barrycxg** [PKU-EPIC/HOTrack#3]
Thanks for your sharing work. It is a great job. I want to test tracking performance on my own dataset. I find in the readme that you mentioned using Curriculum-DeepSDF to initialize SDF models for objects. Can you explain in detail the specific process of generating SDF?  Do I need to train the DeepSDF model on my own data?

Looking forward to your reply！

**Comment by JYChen18** [comment]
Sorry for the late reply. 

DeepSDF can generalize to objects with similar geometry to the training objects. We train several DeepSDF models on different categories, such as bowl, bottle, and can. If your test objects are not included, you should train your DeepSDF on your data.

**Comment by barrycxg** [comment]
Thanks for your patience and reply.
